#!/bin/sh -e

zypper --non-interactive install --force-resolution --no-confirm texlive-scheme-medium
zypper --non-interactive install --force-resolution --no-confirm texlive \
texlive-academicons                       \
texlive-academicons-fonts                 \
texlive-accents                           \
texlive-accsupp                           \
texlive-acro                              \
texlive-addliga                           \
texlive-adobemapping                      \
texlive-albatross                         \
texlive-algobox                           \
texlive-algpseudocodex                    \
texlive-algxpar                           \
texlive-aligned-overset                   \
texlive-alphalph                          \
texlive-amscdx                            \
texlive-annee-scolaire                    \
texlive-answers                           \
texlive-antanilipsum                      \
texlive-arrayjobx                         \
texlive-ascmac                            \
texlive-ascmac-fonts                      \
texlive-atbegshi                          \
texlive-atenddvi                          \
texlive-attachfile2                       \
texlive-atveryend                         \
texlive-auto-pst-pdf                      \
texlive-auto-pst-pdf-doc                  \
texlive-auto-pst-pdf-lua                  \
texlive-auto-pst-pdf-lua-doc              \
texlive-auxhook                           \
texlive-axodraw2-bin                      \
texlive-barracuda                         \
texlive-bclogo                            \
texlive-bezierplot                        \
texlive-bigintcalc                        \
texlive-bitset                            \
texlive-bookmark                          \
texlive-businesscard-qrcode               \
texlive-businesscard-qrcode-doc           \
texlive-bussproofs                        \
texlive-bussproofs-extra                  \
texlive-capt-of                           \
texlive-cascade                           \
texlive-catchfile                         \
texlive-causets                           \
texlive-ccool                             \
texlive-chemplants                        \
texlive-chemsec                           \
texlive-chicago                           \
texlive-chinese-jfm                       \
texlive-chklref                           \
texlive-chklref-bin                       \
texlive-citeref                           \
texlive-cjkpunct                          \
texlive-clojure-pamphlet                  \
texlive-cluttex                           \
texlive-cmbright                          \
texlive-cnltx                             \
texlive-codeanatomy                       \
texlive-collcell                          \
texlive-colorprofiles                     \
texlive-commutative-diagrams              \
texlive-compare                           \
texlive-context                           \
texlive-contour                           \
texlive-cqubeamer                         \
texlive-cslatex                           \
texlive-ctan-o-mat                        \
texlive-ctan-o-mat-bin                    \
texlive-ctan-o-mat-doc                    \
texlive-ctanbib                           \
texlive-ctanbib-bin                       \
texlive-ctanbib-doc                       \
texlive-ctex                              \
texlive-ctex-doc                          \
texlive-curve2e                           \
texlive-cweb-old                          \
texlive-decision-table                    \
texlive-dehyph                            \
texlive-dejavu                            \
texlive-dejavu-doc                        \
texlive-dejavu-fonts                      \
texlive-derivative                        \
texlive-dijkstra                          \
texlive-dtk-bibliography                  \
texlive-dviout-util                       \
texlive-dviout-util-bin                   \
texlive-dynkin-diagrams                   \
texlive-ebgaramond                        \
texlive-ebgaramond-fonts                  \
texlive-ekdosis                           \
texlive-embedfile                         \
texlive-embrac                            \
texlive-emoji                             \
texlive-emojicite                         \
texlive-epstopdf-pkg                      \
texlive-eqexpl                            \
texlive-eqnnumwarn                        \
texlive-erewhon                           \
texlive-erewhon-fonts                     \
texlive-erw-l3                            \
texlive-etexcmds                          \
texlive-etoc                              \
texlive-euclideangeometry                 \
texlive-everysel                          \
texlive-everyshi                          \
texlive-expose-expl3-dunkerque-2019       \
texlive-fandol                            \
texlive-fandol-fonts                      \
texlive-fascicules                        \
texlive-fifo-stack                        \
texlive-firstaid                          \
texlive-fiziko                            \
texlive-fnpct                             \
texlive-fontawesome5                      \
texlive-fontawesome5-fonts                \
texlive-footnotehyper                     \
texlive-forarray                          \
texlive-frenchmath                        \
texlive-frpseudocode                      \
texlive-geometry                          \
texlive-gettitlestring                    \
texlive-git-latexdiff                     \
texlive-git-latexdiff-bin                 \
texlive-git-latexdiff-doc                 \
texlive-glosmathtools                     \
texlive-graphbox                          \
texlive-grfext                            \
texlive-grffile                           \
texlive-helmholtz-ellis-ji-notation       \
texlive-helmholtz-ellis-ji-notation-fonts \
texlive-hologo                            \
texlive-hopatch                           \
texlive-hulipsum                          \
texlive-hycolor                           \
texlive-idxcmds                           \
texlive-ifptex                            \
texlive-ifsym                             \
texlive-imakeidx                          \
texlive-includernw                        \
texlive-infwarerr                         \
texlive-innerscript                       \
texlive-intcalc                           \
texlive-isodate                           \
texlive-jkmath                            \
texlive-jsclasses                         \
texlive-jupynotex                         \
texlive-kanaparser                        \
texlive-ketcindy                          \
texlive-keyfloat                          \
texlive-knuth-lib                         \
texlive-knuth-errata                      \
texlive-knuth-pdf                         \
texlive-kpfonts                           \
texlive-kpfonts-fonts                     \
texlive-kpfonts-otf                       \
texlive-kpfonts-otf-fonts                 \
texlive-kurier                            \
texlive-kurier-fonts                      \
texlive-kvdefinekeys                      \
texlive-kvmap                             \
texlive-kvoptions                         \
texlive-kvsetkeys                         \
texlive-l3backend                         \
texlive-latex-base-dev                    \
texlive-latex-base-dev-doc                \
texlive-latex-graphics-dev                \
texlive-latex-graphics-dev-doc            \
texlive-latex-refsheet                    \
texlive-latex-tools-dev                   \
texlive-latex-tools-dev-doc               \
texlive-latex-via-exemplos                \
texlive-letltxmacro                       \
texlive-letterspacing                     \
texlive-letterswitharrows                 \
texlive-libertine                         \
texlive-libertine-fonts                   \
texlive-libertinus-otf                    \
texlive-lie-hasse                         \
texlive-light-latex-make                  \
texlive-light-latex-make-bin              \
texlive-light-latex-make-doc              \
texlive-linegoal                          \
texlive-localloc                          \
texlive-ltablex                           \
texlive-ltabptch                          \
texlive-ltxcmds                           \
texlive-lua-typo                          \
texlive-lua-uca                           \
texlive-lua-ul                            \
texlive-lua-uni-algos                     \
texlive-luacolor                          \
texlive-luahbtex                          \
texlive-luaimageembed                     \
texlive-luajittex                         \
texlive-luakeys                           \
texlive-lualatex-truncate                 \
texlive-luaprogtable                      \
texlive-luarandom                         \
texlive-luatexja                          \
texlive-luavlna                           \
texlive-ly1                               \
texlive-macros2e                          \
texlive-makecell                          \
texlive-makerobust                        \
texlive-manfnt                            \
texlive-manfnt-font                       \
texlive-matapli                           \
texlive-mathcommand                       \
texlive-mathfixs                          \
texlive-mathlig                           \
texlive-matrix-skeleton                   \
texlive-membranecomputing                 \
texlive-memorygraphs                      \
texlive-metapost-colorbrewer              \
texlive-minifp                            \
texlive-minted                            \
texlive-mismath                           \
texlive-mnsymbol                          \
texlive-mnsymbol-fonts                    \
texlive-modes                             \
texlive-modulus                           \
texlive-musicography                      \
texlive-na-position                       \
texlive-namedef                           \
texlive-newfloat                          \
texlive-newpax                            \
texlive-nicematrix                        \
texlive-nth                               \
texlive-numberpt                          \
texlive-numerica                          \
texlive-ocg-p                             \
texlive-ocgx                              \
texlive-optex                             \
texlive-outerhbox                         \
texlive-overpic                           \
texlive-padcount                          \
texlive-pagesel                           \
texlive-paracol                           \
texlive-parnotes                          \
texlive-pdf14                             \
texlive-pdf14-doc                         \
texlive-pdfarticle                        \
texlive-pdfarticle-doc                    \
texlive-pdfcolmk                          \
texlive-pdfcomment                        \
texlive-pdfescape                         \
texlive-pdflscape                         \
texlive-pdflscape-doc                     \
texlive-pdfmanagement-testphase           \
texlive-pdftex-quiet                      \
texlive-pdftexcmds                        \
texlive-pdftosrc                          \
texlive-perltex                           \
texlive-perltex-bin                       \
texlive-perltex-doc                       \
texlive-physconst                         \
texlive-physunits                         \
texlive-picture                           \
texlive-pinoutikz                         \
texlive-plantuml                          \
texlive-platex                            \
texlive-platex-bin                        \
texlive-platex-tools                      \
texlive-pm-isomath                        \
texlive-polexpr                           \
texlive-poormanlog                        \
texlive-prelim2e                          \
texlive-principia                         \
texlive-profcollege                       \
texlive-proof-at-the-end                  \
texlive-ps2eps                            \
texlive-ps2eps-bin                        \
texlive-pseudo                            \
texlive-pst-calculate                     \
texlive-ptex                              \
texlive-ptex-base                         \
texlive-ptex-bin                          \
texlive-ptex-fonts                        \
texlive-pwebmac                           \
texlive-qrcode                            \
texlive-qsharp                            \
texlive-quran-de                          \
texlive-ragged2e                          \
texlive-raleway                           \
texlive-raleway-fonts                     \
texlive-random                            \
texlive-rank-2-roots                      \
texlive-refcount                          \
texlive-rerunfilecheck                    \
texlive-rest-api                          \
texlive-rest-api-doc                      \
texlive-rojud                             \
texlive-rojud-fonts                       \
texlive-ruler                             \
texlive-sankey                            \
texlive-sansmathaccent                    \
texlive-schulmathematik                   \
texlive-scontents                         \
texlive-scratchx                          \
texlive-selinput                          \
texlive-shadethm                          \
texlive-shadowtext                        \
texlive-short-math-guide                  \
texlive-sidecap                           \
texlive-simplebnf                         \
texlive-simplekv                          \
texlive-smartdiagram                      \
texlive-soulpos                           \
texlive-spix                              \
texlive-stackengine                       \
texlive-statistics                        \
texlive-statistik                         \
texlive-statmath                          \
texlive-stricttex                         \
texlive-stringenc                         \
texlive-structmech                        \
texlive-sttools                           \
texlive-subtext                           \
texlive-swrule                            \
texlive-tabto-ltx                         \
texlive-tabu                              \
texlive-tagging                           \
texlive-tagpdf                            \
texlive-tasks                             \
texlive-tcolorbox                         \
texlive-tensind                           \
texlive-termcal                           \
texlive-termcal-de                        \
texlive-tetragonos                        \
texlive-tex-nutshell                      \
texlive-texdate                           \
texlive-texdoctk                          \
texlive-texonly                           \
texlive-texplate                          \
texlive-texshade                          \
texlive-thmtools                          \
texlive-threeparttable                    \
texlive-tikz-cd                           \
texlive-tlmgrbasics                       \
texlive-translator                        \
texlive-transparent                       \
texlive-truncate                          \
texlive-typewriter                        \
texlive-uninormalize                      \
texlive-uniquecounter                     \
texlive-uplatex                           \
texlive-uptex                             \
texlive-uptex-base                        \
texlive-uptex-fonts                       \
texlive-uri                               \
texlive-verifica                          \
texlive-verse                             \
texlive-wallpaper                         \
texlive-wasy-type1                        \
texlive-wasy-type1-fonts                  \
texlive-witharrows                        \
texlive-xcjk2uni                          \
texlive-xcomment                          \
texlive-xechangebar                       \
texlive-xelatex-dev                       \
texlive-xelatex-dev-bin                   \
texlive-xii-lat                           \
texlive-xindex                            \
texlive-xint                              \
texlive-xpinyin                           \
texlive-xsim                              \
texlive-yquant                            \
texlive-zapfding-fonts                    \
texlive-zbmath-review-template            \
texlive-zhmetrics                         \
texlive-zhmetrics-uptex                   \
texlive-zhnumber                          \
texlive-zref                              \
texlive-zwpagelayout                      \
texlive-zztex                             \
texlive-collection-mathscience            \
texlive-collection-langenglish            \
texlive-collection-langeuropean

zypper install -y 'tex(beamer.cls)'
zypper install -y 'tex(pzdr.tfm)'
zypper install -y 'tex(fancyvrb.sty)'
zypper install -y 'tex(framed.sty)'

#needed for biber
zypper install -y perl-Parse-RecDescent

# currently not available

#texlive-context-algorithmic               
#texlive-context-handlecsv      
#texlive-expkv                             
#texlive-expkv-cs                          
#texlive-expkv-def                         
#texlive-expkv-opt                          
#texlive-startlatex2e                      
#texlive-soulutf8                                    
