#!/bin/sh -e

zypper --non-interactive install --force-resolution --no-confirm texlive-scheme-basic
zypper --non-interactive install --force-resolution --no-confirm texlive \
texlive-12many \
texlive-a0poster \
texlive-a2ping \
texlive-a4wide \
texlive-abbr \
texlive-abstyles \
texlive-accfonts \
texlive-adhocfilelist \
texlive-adjustbox \
texlive-advdate \
texlive-ae \
texlive-aeguill \
texlive-afm2pl \
texlive-alg \
texlive-algorithm2e \
texlive-algorithmicx \
texlive-algorithms \
texlive-amscls \
texlive-amsfonts \
texlive-amsfonts-fonts \
texlive-amslatex-primer \
texlive-amsldoc-it \
texlive-amsmath \
texlive-amsmath-it \
texlive-amstex \
texlive-amsthdoc-it \
texlive-animate \
texlive-anysize \
texlive-apalike-german \
texlive-apnum \
texlive-appendixnumberbeamer \
texlive-apprends-latex \
texlive-apxproof \
texlive-arabxetex \
texlive-arara \
texlive-armtex \
texlive-armtex-fonts \
texlive-around-the-bend \
texlive-arphic \
texlive-arphic-fonts \
texlive-arydshln \
texlive-ascii-chart \
texlive-asymptote \
texlive-autoaligne \
texlive-autobreak \
texlive-automata \
texlive-avantgar \
texlive-avantgar-fonts \
texlive-awesomebox \
texlive-axodraw2 \
texlive-babel \
texlive-babel-albanian \
texlive-babel-basque \
texlive-babel-bosnian \
texlive-babel-breton \
texlive-babel-catalan \
texlive-babel-croatian \
texlive-babel-czech \
texlive-babel-danish \
texlive-babel-dutch \
texlive-babel-english \
texlive-babel-estonian \
texlive-babel-finnish \
texlive-babel-french \
texlive-babel-friulan \
texlive-babel-galician \
texlive-babel-german \
texlive-babel-hebrew \
texlive-babel-hungarian \
texlive-babel-icelandic \
texlive-babel-irish \
texlive-babel-italian \
texlive-babel-kurmanji \
texlive-babel-latin \
texlive-babel-latvian \
texlive-babel-macedonian \
texlive-babel-norsk \
texlive-babel-occitan \
texlive-babel-piedmontese \
texlive-babel-polish \
texlive-babel-portuges \
texlive-babel-romanian \
texlive-babel-romansh \
texlive-babel-samin \
texlive-babel-scottish \
texlive-babel-slovak \
texlive-babel-slovenian \
texlive-babel-spanish \
texlive-babel-swedish \
texlive-babel-turkish \
texlive-babel-welsh \
texlive-babelbib \
texlive-background \
texlive-backnaur \
texlive-barr \
texlive-basque-book \
texlive-basque-date \
texlive-bbcard \
texlive-bbding \
texlive-bbm \
texlive-bbm-macros \
texlive-bbold \
texlive-beamer \
texlive-beamer-tut-pt \
texlive-begriff \
texlive-bera \
texlive-bera-fonts \
texlive-beton \
texlive-bguq \
texlive-bguq-fonts \
texlive-bib-fr \
texlive-biber \
texlive-biber-bin \
texlive-biblatex \
texlive-biblatex-cheatsheet \
texlive-bibleref \
texlive-bibleref-french \
texlive-bibleref-german \
texlive-bibtex \
texlive-bibtex8 \
texlive-bibtexu \
texlive-bibtex-bin \
texlive-bibtexu-bin \
texlive-bibunits \
texlive-bidi \
texlive-bidi-atbegshi \
texlive-bidicontour \
texlive-bidipagegrid \
texlive-bidipresentation \
texlive-bidishadowtext \
texlive-bigfoot \
texlive-biocon \
texlive-bitelist \
texlive-bitpattern \
texlive-blockdraw_mp \
texlive-bohr \
texlive-boldtensors \
texlive-bookman \
texlive-bookman-fonts \
texlive-booktabs \
texlive-booktabs-de \
texlive-booktabs-fr \
texlive-boondox \
texlive-boondox-fonts \
texlive-borceux \
texlive-bosisio \
texlive-boxedminipage \
texlive-bpchem \
texlive-bpolynomial \
texlive-braket \
texlive-breakcites \
texlive-breakurl \
texlive-bredzenie \
texlive-breqn \
texlive-bropd \
texlive-bundledoc \
texlive-bytefield \
texlive-c-pascal \
texlive-calculation \
texlive-cancel \
texlive-caption \
texlive-carlisle \
texlive-catcodes \
texlive-cc-pl \
texlive-cc-pl-fonts \
texlive-ccaption \
texlive-ccfonts \
texlive-changepage \
texlive-charter \
texlive-charter-fonts \
texlive-checkcites \
texlive-checklistings \
texlive-chemarrow \
texlive-chemarrow-fonts \
texlive-chemcompounds \
texlive-chemcono \
texlive-chemexec \
texlive-chemfig \
texlive-chemformula \
texlive-chemgreek \
texlive-chemmacros \
texlive-chemnum \
texlive-chemschemex \
texlive-chemstyle \
texlive-chickenize \
texlive-chktex \
texlive-chngcntr \
texlive-chronosys \
texlive-cite \
texlive-cjk \
texlive-cjk-ko \
texlive-cleveref \
texlive-cloze \
texlive-clrscode \
texlive-clrscode3e \
texlive-cm \
texlive-cm-super \
texlive-cm-super-fonts \
texlive-cmap \
texlive-cmarrows \
texlive-cmexb \
texlive-cmexb-fonts \
texlive-cmextra \
texlive-cnbwp \
texlive-cns \
texlive-codicefiscaleitaliano \
texlive-collectbox \
texlive-collection-basic \
texlive-collection-context \
texlive-collection-fontsrecommended \
texlive-collection-fontutils \
texlive-collection-latex \
texlive-collection-latexrecommended \
texlive-collection-luatex \
texlive-collection-xetex \
texlive-colorsep \
texlive-colortbl \
texlive-combofont \
texlive-commath \
texlive-comment \
texlive-complexity \
texlive-components-of-TeX \
texlive-comprehensive \
texlive-computational-complexity \
texlive-concmath \
texlive-concrete \
texlive-conteq \
texlive-context \
texlive-context-account \
texlive-context-algorithmic \
texlive-context-animation \
texlive-context-annotation \
texlive-context-bnf \
texlive-context-chromato \
texlive-context-cmscbf \
texlive-context-cmttbf \
texlive-context-construction-plan \
texlive-context-cyrillicnumbers \
texlive-context-degrade \
texlive-context-fancybreak \
texlive-context-filter \
texlive-context-fonts \
texlive-context-french \
texlive-context-fullpage \
texlive-context-gantt \
texlive-context-gnuplot \
texlive-context-inifile \
texlive-context-layout \
texlive-context-letter \
texlive-context-lettrine \
texlive-context-mathsets \
texlive-context-notes-zh-cn \
texlive-context-rst \
texlive-context-ruby \
texlive-context-simplefonts \
texlive-context-simpleslides \
texlive-context-title \
texlive-context-transliterator \
texlive-context-typearea \
texlive-context-typescripts \
texlive-context-vim \
texlive-context-visualcounter \
texlive-coollist \
texlive-coolstr \
texlive-correctmathalign \
texlive-courier \
texlive-courier-fonts \
texlive-courier-scaled \
texlive-crop \
texlive-cryptocode \
texlive-cs \
texlive-cs-fonts \
texlive-csbulletin \
texlive-cslatex \
texlive-csplain \
texlive-csquotes \
texlive-csquotes-de \
texlive-cstex \
texlive-cstypo \
texlive-ctable \
texlive-ctablestack \
texlive-ctan_chk \
texlive-ctanify \
texlive-ctanupload \
texlive-ctie \
texlive-currfile \
texlive-cursolatex \
texlive-curves \
texlive-cweb \
texlive-datatool \
texlive-datetime2 \
texlive-de-macro \
texlive-dehyph-exptl \
texlive-delim \
texlive-delimseasy \
texlive-delimset \
texlive-detex \
texlive-dhua \
texlive-dickimaw \
texlive-diffcoeff \
texlive-digiconfigs \
texlive-dinat \
texlive-dingbat \
texlive-dirtree \
texlive-dosepsbin \
texlive-dot2texi \
texlive-dowith \
texlive-draftcopy \
texlive-drawmatrix \
texlive-drawstack \
texlive-droit-fr \
texlive-drv \
texlive-dtl \
texlive-dtxgen \
texlive-dtxtut \
texlive-dviasm \
texlive-dvicopy \
texlive-dvidvi \
texlive-dviincl \
texlive-dviinfox \
texlive-dviljk \
texlive-dvipdfmx \
texlive-dvipng \
texlive-dvipos \
texlive-dvips \
texlive-dvipsconfig \
texlive-dvisvgm \
texlive-dyntree \
texlive-e-french \
texlive-ebproof \
texlive-ec \
texlive-econometrics \
texlive-eepic \
texlive-efbox \
texlive-eijkhout \
texlive-elements \
texlive-ellipsis \
texlive-elocalloc \
texlive-eltex \
texlive-emf \
texlive-emp \
texlive-enctex \
texlive-encxvlna \
texlive-endfloat \
texlive-endiagram \
texlive-engrec \
texlive-engtlc \
texlive-enigma \
texlive-enumitem \
texlive-environ \
texlive-epigram \
texlive-epsf \
texlive-epsf-dvipdfmx \
texlive-epsincl \
texlive-epslatex-fr \
texlive-epstopdf \
texlive-eqnarray \
texlive-es-tex-faq \
texlive-eso-pic \
texlive-esvect \
texlive-esvect-fonts \
texlive-etdipa \
texlive-etex \
texlive-etex-pkg \
texlive-etextools \
texlive-etoolbox \
texlive-etoolbox-de \
texlive-euenc \
texlive-euler \
texlive-euro \
texlive-euro-ce \
texlive-eurosym \
texlive-eurosym-fonts \
texlive-everyhook \
texlive-everypage \
texlive-expressg \
texlive-extarrows \
texlive-exteps \
texlive-extpfeil \
texlive-extratools \
texlive-extsizes \
texlive-facture \
texlive-faktor \
texlive-fancybox \
texlive-fancyhdr \
texlive-fancyhdr-it \
texlive-fancylabel \
texlive-fancyref \
texlive-fancyvrb \
texlive-featpost \
texlive-fenixpar \
texlive-feupphdteses \
texlive-feynmf \
texlive-feynmp-auto \
texlive-fifinddo-info \
texlive-figflow \
texlive-filecontents \
texlive-filehook \
texlive-filemod \
texlive-filesystem \
texlive-finbib \
texlive-findhyph \
texlive-finstrut \
texlive-fix2col \
texlive-fixlatvian \
texlive-fixltxhyph \
texlive-fixpdfmag \
texlive-float \
texlive-floatrow \
texlive-fltpoint \
texlive-fmtcount \
texlive-fnpara \
texlive-fnspe \
texlive-fntproof \
texlive-font-change \
texlive-font-change-xetex \
texlive-fontawesome \
texlive-fontawesome-fonts \
texlive-fontaxes \
texlive-fontbook \
texlive-fontch \
texlive-fontinst \
texlive-fontname \
texlive-fontools \
texlive-fonts-tlwg \
texlive-fonts-tlwg-fonts \
texlive-fontspec \
texlive-fontware \
texlive-fontwrap \
texlive-footmisc \
texlive-forest \
texlive-forest-quickstart \
texlive-forloop \
texlive-formation-latex-ul \
texlive-fouridx \
texlive-fp \
texlive-fpl \
texlive-fpl-fonts \
texlive-fragmaster \
texlive-framed \
texlive-frletter \
texlive-frontespizio \
texlive-functan \
texlive-fvextra \
texlive-galois \
texlive-garrigues \
texlive-garuda-c90 \
texlive-gastex \
texlive-gates \
texlive-gene-logic \
texlive-gentle \
texlive-geometry \
texlive-german \
texlive-germbib \
texlive-germkorr \
texlive-getoptk \
texlive-gfnotation \
texlive-ghsystem \
texlive-gincltex \
texlive-gloss-occitan \
texlive-glossaries \
texlive-glossaries-english \
texlive-glossaries-german \
texlive-glyphlist \
texlive-gmp \
texlive-gobble \
texlive-gotoh \
texlive-graphics \
texlive-graphics-cfg \
texlive-graphics-def \
texlive-graphics-pln \
texlive-greek-fontenc \
texlive-grundgesetze \
texlive-gsftopk \
texlive-gtl \
texlive-gu \
texlive-guide-to-latex \
texlive-gustlib \
texlive-gustprog \
texlive-happy4th \
texlive-hatching \
texlive-hausarbeit-jura \
texlive-helvetic \
texlive-helvetic-fonts \
texlive-hep \
texlive-hepnames \
texlive-hepparticles \
texlive-hepthesis \
texlive-hepunits \
texlive-heuristica \
texlive-heuristica-fonts \
texlive-hlist \
texlive-hook-pre-commit-pkg \
texlive-hrlatex \
texlive-hyperref \
texlive-hyph-utf8 \
texlive-hyphen-ancientgreek \
texlive-hyphen-base \
texlive-hyphen-basque \
texlive-hyphen-catalan \
texlive-hyphen-croatian \
texlive-hyphen-czech \
texlive-hyphen-danish \
texlive-hyphen-dutch \
texlive-hyphen-english \
texlive-hyphen-estonian \
texlive-hyphen-finnish \
texlive-hyphen-french \
texlive-hyphen-friulan \
texlive-hyphen-galician \
texlive-hyphen-german \
texlive-hyphen-greek \
texlive-hyphen-hungarian \
texlive-hyphen-icelandic \
texlive-hyphen-irish \
texlive-hyphen-italian \
texlive-hyphen-kurmanji \
texlive-hyphen-latin \
texlive-hyphen-latvian \
texlive-hyphen-lithuanian \
texlive-hyphen-norwegian \
texlive-hyphen-occitan \
texlive-hyphen-piedmontese \
texlive-hyphen-polish \
texlive-hyphen-portuguese \
texlive-hyphen-romanian \
texlive-hyphen-romansh \
texlive-hyphen-slovak \
texlive-hyphen-slovenian \
texlive-hyphen-spanish \
texlive-hyphen-swedish \
texlive-hyphen-turkish \
texlive-hyphen-uppersorbian \
texlive-hyphen-welsh \
texlive-hyphenat \
texlive-hyphenex \
texlive-hyplain \
texlive-ifmtarg \
texlive-ifoddpage \
texlive-ifplatform \
texlive-iftex \
texlive-impatient \
texlive-impatient-fr \
texlive-impnattypo \
texlive-import \
texlive-index \
texlive-inlinedef \
texlive-insbox \
texlive-interchar \
texlive-interpreter \
texlive-interval \
texlive-intro-scientific \
texlive-ionumbers \
texlive-isomath \
texlive-itnumpar \
texlive-jknapltx \
texlive-jmn \
texlive-jmn-fonts \
texlive-js-misc \
texlive-jurabib \
texlive-juramisc \
texlive-kantlipsum \
texlive-karnaugh \
texlive-karnaugh-map \
texlive-karnaughmap \
texlive-kastrup \
texlive-knuth-lib \
texlive-knuth-local \
texlive-koma-script \
texlive-koma-script-examples \
texlive-kotex-utf \
texlive-kpathsea \
texlive-l2picfaq \
texlive-l2tabu \
texlive-l2tabu-english \
texlive-l2tabu-french \
texlive-l2tabu-italian \
texlive-l2tabu-spanish \
texlive-l3experimental \
texlive-l3kernel \
texlive-l3packages \
texlive-lacheck \
texlive-lambda-lists \
texlive-langcode \
texlive-latex \
texlive-latex-brochure \
texlive-latex-course \
texlive-latex-fonts \
texlive-latex-git-log \
texlive-latex-graphics-companion \
texlive-latex-papersize \
texlive-latex-veryshortguide \
texlive-latex-web-companion \
texlive-latex2e-help-texinfo \
texlive-latex2e-help-texinfo-fr \
texlive-latex2e-help-texinfo-spanish \
texlive-latex2man \
texlive-latex2nemeth \
texlive-latex4wp \
texlive-latex4wp-it \
texlive-latexbug \
texlive-latexcheat \
texlive-latexcheat-de \
texlive-latexcheat-esmx \
texlive-latexcheat-ptbr \
texlive-latexconfig \
texlive-latexcourse-rug \
texlive-latexdiff \
texlive-latexfileinfo-pkgs \
texlive-latexfileversion \
texlive-latexindent \
texlive-latexmk \
texlive-latexmp \
texlive-latexpand \
texlive-layaureo \
texlive-lcdftypetools \
texlive-lecturer \
texlive-lettrine \
texlive-librarian \
texlive-lineno \
texlive-lipsum \
texlive-listings \
texlive-listings-ext \
texlive-listofitems \
texlive-lithuanian \
texlive-lm \
texlive-lm-fonts \
texlive-lm-math \
texlive-lm-math-fonts \
texlive-logicproof \
texlive-logreq \
texlive-longdivision \
texlive-lpform \
texlive-lplfitch \
texlive-lshort-czech \
texlive-lshort-dutch \
texlive-lshort-english \
texlive-lshort-estonian \
texlive-lshort-finnish \
texlive-lshort-french \
texlive-lshort-german \
texlive-lshort-italian \
texlive-lshort-polish \
texlive-lshort-portuguese \
texlive-lshort-slovak \
texlive-lshort-slovenian \
texlive-lshort-spanish \
texlive-lshort-turkish \
texlive-lstbayes \
texlive-ltxfileinfo \
texlive-ltximg \
texlive-ltxmisc \
texlive-lua-alt-getopt \
texlive-lua-check-hyphen \
texlive-lua-visual-debug \
texlive-luabibentry \
texlive-luabidi \
texlive-luacode \
texlive-luahyphenrules \
texlive-luaindex \
texlive-luainputenc \
texlive-luaintro \
texlive-lualatex-math \
texlive-lualibs \
texlive-luamplib \
texlive-luaotfload \
texlive-luapackageloader \
texlive-luasseq \
texlive-luatex \
texlive-luatex85 \
texlive-luatexbase \
texlive-luatexko \
texlive-luatextra \
texlive-luatodonotes \
texlive-luaxml \
texlive-lwarp \
texlive-ly1 \
texlive-macros2e \
texlive-mafr \
texlive-make4ht \
texlive-makecmds \
texlive-makeindex \
texlive-manfnt \
texlive-manfnt-font \
texlive-manfnt-font-fonts \
texlive-marginnote \
texlive-marvosym \
texlive-marvosym-fonts \
texlive-match_parens \
texlive-math-into-latex-4 \
texlive-mathcomp \
texlive-mathdots \
texlive-mathpartir \
texlive-mathpazo \
texlive-mathpazo-fonts \
texlive-mathpunctspace \
texlive-maths-symbols \
texlive-mathspec \
texlive-mathtools \
texlive-matlab-prettifier \
texlive-mattens \
texlive-mcf2graph \
texlive-mdframed \
texlive-mdwtools \
texlive-media9 \
texlive-memdesign \
texlive-memoir \
texlive-MemoirChapStyles \
texlive-metafont \
texlive-metafont-beginners \
texlive-metago \
texlive-metalogo \
texlive-metaobj \
texlive-metaplot \
texlive-metapost \
texlive-metapost-examples \
texlive-metapost-fonts \
texlive-metatex \
texlive-metatype1 \
texlive-metauml \
texlive-mex \
texlive-mf2pt1 \
texlive-mfirstuc \
texlive-mflogo \
texlive-mflogo-font \
texlive-mflogo-font-fonts \
texlive-mflua \
texlive-mfnfss \
texlive-mfpic \
texlive-mfpic4ode \
texlive-mfware \
texlive-mgltex \
texlive-mhchem \
texlive-mhequ \
texlive-microtype \
texlive-microtype-de \
texlive-midnight \
texlive-miller \
texlive-milog \
texlive-minitoc \
texlive-mkjobtexmf \
texlive-mkpattern \
texlive-moderncv \
texlive-morefloats \
texlive-moreverb \
texlive-movie15 \
texlive-mp3d \
texlive-mparhack \
texlive-mparrows \
texlive-mpattern \
texlive-mpcolornames \
texlive-mpgraphics \
texlive-mptopdf \
texlive-mptrees \
texlive-ms \
texlive-msg \
texlive-multido \
texlive-multiobjective \
texlive-multirow \
texlive-mwcls \
texlive-mweights \
texlive-nag \
texlive-natbib \
texlive-natded \
texlive-nath \
texlive-navigator \
texlive-ncctools \
texlive-ncntrsbk \
texlive-ncntrsbk-fonts \
texlive-needspace \
texlive-nevelok \
texlive-newsletr \
texlive-newtx \
texlive-newtx-fonts \
texlive-newunicodechar \
texlive-nodetree \
texlive-norasi-c90 \
texlive-notoccite \
texlive-ntgclass \
texlive-ntheorem \
texlive-nuc \
texlive-nucleardata \
texlive-numprint \
texlive-oberdiek \
texlive-objectz \
texlive-ocgx2 \
texlive-odsfile \
texlive-ofs \
texlive-olsak-misc \
texlive-oplotsymbl \
texlive-optional \
texlive-ordinalpt \
texlive-ot-tableau \
texlive-oubraces \
texlive-palatino \
texlive-palatino-fonts \
texlive-paracol \
texlive-paralist \
texlive-parallel \
texlive-parskip \
texlive-patgen \
texlive-patgen2-tutorial \
texlive-path \
texlive-pbox \
texlive-pdf-trans \
texlive-pdfbook2 \
texlive-pdfcrop \
texlive-pdfjam \
texlive-pdflatexpicscale \
texlive-pdfpages \
texlive-pdftex \
texlive-pdftex-fonts \
texlive-pdfxup \
texlive-perfectcut \
texlive-pfarrei \
texlive-pgf \
texlive-pgfgantt \
texlive-pgfopts \
texlive-pgfplots \
texlive-philokalia \
texlive-philokalia-fonts \
texlive-physics \
texlive-pict2e \
texlive-pictexsum \
texlive-piechartmp \
texlive-pitex \
texlive-pkfix \
texlive-pkfix-helper \
texlive-pl \
texlive-pl-fonts \
texlive-placeat \
texlive-placeins \
texlive-placeins-plain \
texlive-plain \
texlive-plainpkg \
texlive-plipsum \
texlive-plnfss \
texlive-plstmary \
texlive-polski \
texlive-polyglossia \
texlive-powerdot \
texlive-present \
texlive-preview \
texlive-prftree \
texlive-printlen \
texlive-proba \
texlive-prooftrees \
texlive-przechlewski-book \
texlive-ps2pk \
texlive-pseudocode \
texlive-psfrag \
texlive-psfrag-italian \
texlive-pslatex \
texlive-psnfss \
texlive-pspicture \
texlive-pst-3d \
texlive-pst-blur \
texlive-pst-coil \
texlive-pst-eps \
texlive-pst-fill \
texlive-pst-grad \
texlive-pst-math \
texlive-pst-node \
texlive-pst-ovl \
texlive-pst-pdf \
texlive-pst-plot \
texlive-pst-slpe \
texlive-pst-text \
texlive-pst-tree \
texlive-pstricks \
texlive-pstricks-add \
texlive-ptext \
texlive-purifyeps \
texlive-pxfonts \
texlive-pxfonts-fonts \
texlive-pygmentex \
texlive-pythonhighlight \
texlive-pythontex \
texlive-qpxqtx \
texlive-qstest \
texlive-quran \
texlive-r_und_s \
texlive-raleway \
texlive-randomlist \
texlive-rcs \
texlive-realscripts \
texlive-rec-thy \
texlive-regexpatch \
texlive-relsize \
texlive-repere \
texlive-resumemac \
texlive-revquantum \
texlive-revtex4 \
texlive-ribbonproofs \
texlive-rmathbr \
texlive-roex \
texlive-roundrect \
texlive-rsfs \
texlive-rsfs-fonts \
texlive-ruhyphen \
texlive-sansmath \
texlive-sasnrdisplay \
texlive-sauerj \
texlive-scalerel \
texlive-schemata \
texlive-sciposter \
texlive-sclang-prettifier \
texlive-scripts \
texlive-scripts-extra \
texlive-section \
texlive-sectsty \
texlive-seetexk \
texlive-selnolig \
texlive-seminar \
texlive-sepnum \
texlive-sesamanuel \
texlive-setspace \
texlive-sfg \
texlive-shade \
texlive-shadow \
texlive-shapes \
texlive-showexpl \
texlive-showhyphens \
texlive-shuffle \
texlive-simple-resume-cv \
texlive-simple-thesis-dissertation \
texlive-simpler-wick \
texlive-simplewick \
texlive-simplified-latex \
texlive-SIstyle \
texlive-SIunits \
texlive-siunitx \
texlive-skmath \
texlive-slideshow \
texlive-smartdiagram \
texlive-soul \
texlive-sourcecodepro \
texlive-sourcecodepro-fonts \
texlive-spalign \
texlive-spelling \
texlive-splines \
texlive-srcredact \
texlive-standalone \
texlive-stanli \
texlive-statex \
texlive-statex2 \
texlive-steinmetz \
texlive-stmaryrd \
texlive-stmaryrd-fonts \
texlive-struktex \
texlive-sty2dtx \
texlive-suanpan \
texlive-subdepth \
texlive-subfig \
texlive-subfigure \
texlive-substances \
texlive-substr \
texlive-subsupscripts \
texlive-supertabular \
texlive-susy \
texlive-svg-inkscape \
texlive-svn-prov \
texlive-swebib \
texlive-syllogism \
texlive-symbol \
texlive-symbol-fonts \
texlive-synctex \
texlive-synproof \
texlive-systeme \
texlive-t-angles \
texlive-t2 \
texlive-tablor \
texlive-tabto-generic \
texlive-tabulary \
texlive-tabvar \
texlive-tabvar-fonts \
texlive-tamethebeast \
texlive-tap \
texlive-tds \
texlive-tdsfrmath \
texlive-templates-fenn \
texlive-templates-sommer \
texlive-tensor \
texlive-termmenu \
texlive-tex \
texlive-tex-ewd \
texlive-tex-font-errors-cheatsheet \
texlive-tex-gyre \
texlive-tex-gyre-fonts \
texlive-tex-gyre-math \
texlive-tex-gyre-math-fonts \
texlive-tex-ini-files \
texlive-tex-overview \
texlive-tex-ps \
texlive-tex-refs \
texlive-tex-virtual-academy-pl \
texlive-tex4ebook \
texlive-tex4ht \
texlive-texapi \
texlive-texbytopic \
texlive-texcount \
texlive-texdef \
texlive-texdiff \
texlive-texdirflatten \
texlive-texdoc \
texlive-texfot \
texlive-texinfo \
texlive-texlive-common \
texlive-texlive-cz \
texlive-texlive-de \
texlive-texlive-en \
texlive-texlive-es \
texlive-texlive-fr \
texlive-texlive-it \
texlive-texlive-pl \
texlive-texlive.infra \
texlive-texliveonfly \
texlive-texloganalyser \
texlive-texosquery \
texlive-textcase \
texlive-textgreek \
texlive-textopo \
texlive-textpath \
texlive-texware \
texlive-thmbox \
texlive-threeddice \
texlive-thumbpdf \
texlive-tie \
texlive-tikz-3dplot \
texlive-times \
texlive-times-fonts \
texlive-timetable \
texlive-tipa \
texlive-tipa-de \
texlive-tipa-fonts \
texlive-titlepages \
texlive-titlesec \
texlive-titling \
texlive-tkz-tab \
texlive-tlc2 \
texlive-tocbibind \
texlive-todonotes \
texlive-tools \
texlive-tpic2pdftex \
texlive-tracklang \
texlive-translation-array-fr \
texlive-translation-arsclassica-de \
texlive-translation-biblatex-de \
texlive-translation-chemsym-de \
texlive-translation-dcolumn-fr \
texlive-translation-ecv-de \
texlive-translation-enumitem-de \
texlive-translation-europecv-de \
texlive-translation-filecontents-de \
texlive-translation-moreverb-de \
texlive-translation-natbib-fr \
texlive-translation-tabbing-fr \
texlive-translations \
texlive-treetex \
texlive-trigonometry \
texlive-trimspaces \
texlive-ttfutils \
texlive-turkmen \
texlive-turnstile \
texlive-txfonts \
texlive-txfonts-fonts \
texlive-type1cm \
texlive-Type1fonts \
texlive-typehtml \
texlive-typeoutfileinfo \
texlive-ucharcat \
texlive-ucharclasses \
texlive-ucs \
texlive-udesoftec \
texlive-uhc \
texlive-uhc-fonts \
texlive-uhrzeit \
texlive-ukrhyph \
texlive-ulem \
texlive-ulqda \
texlive-umlaute \
texlive-undergradmath \
texlive-underscore \
texlive-unicode-bidi \
texlive-unicode-data \
texlive-unicode-math \
texlive-unisugar \
texlive-units \
texlive-unitsdef \
texlive-upca \
texlive-updmap-map \
texlive-upquote \
texlive-url \
texlive-utf8mex \
texlive-utopia \
texlive-utopia-fonts \
texlive-variations \
texlive-varisize \
texlive-varwidth \
texlive-venn \
texlive-visualfaq \
texlive-visualtikz \
texlive-vlna \
texlive-voss-mathcol \
texlive-wadalab \
texlive-wadalab-fonts \
texlive-was \
texlive-wasy \
texlive-wasysym \
texlive-web \
texlive-webguide \
texlive-wrapfig \
texlive-xargs \
texlive-xcolor \
texlive-xdvi \
texlive-xebaposter \
texlive-xecjk \
texlive-xecolor \
texlive-xecyr \
texlive-xeindex \
texlive-xesearch \
texlive-xespotcolor \
texlive-xetex \
texlive-xetex-itrans \
texlive-xetex-pstricks \
texlive-xetex-tibetan \
texlive-xetexconfig \
texlive-xetexfontinfo \
texlive-xetexko \
texlive-xetexref \
texlive-xevlna \
texlive-xfor \
texlive-xifthen \
texlive-xii \
texlive-xkeyval \
texlive-xlop \
texlive-xltxtra \
texlive-xpatch \
texlive-xpdfopen \
texlive-xstring \
texlive-xtab \
texlive-xunicode \
texlive-xymtex \
texlive-xypic-tut-pt \
texlive-yax \
texlive-yhmath \
texlive-yhmath-fonts \
texlive-youngtab \
texlive-ytableau \
texlive-zapfchan \
texlive-zapfchan-fonts \
texlive-zapfding \
texlive-zapfding-fonts

zypper install -y 'tex(beamer.cls)'
zypper install -y 'tex(pzdr.tfm)'
zypper install -y 'tex(fancyvrb.sty)'
zypper install -y 'tex(framed.sty)'

zypper install -y perl-Parse-RecDescent
