name: Docker Build

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        #runs-on: opensuse/leap
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push Docker image
          run: |
            TAGNAME="pbielefeldt/latexos"
            TAGVERSION="15.5_testtesttest"

            cd LaTexOS
            if [ "${{ github.event_name }}" == "pull_request" ]; then
                #TAGVERSION="${TAGVERSION}:testing_${{ github.head_ref }}"
                TAGVERSION="${TAGVERSION}-testing"
            fi
            
            docker buildx build --platform linux/amd64 --tag ${TAGNAME}:${TAGVERSION} --tag ${TAGNAME}:latest .
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker push ${TAGNAME} --all-tags
