name: "Build/Test/Push LaTexOS Docker Image"

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        #runs-on: opensuse/leap
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # - name: Login to GitHub Container Registry
            #   uses: docker/login-action@v3
            #   with:
            #     username: ${{ secrets.GITHUB_ACTOR }}
            #     password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build Docker image
              id: build_image
              run: |
                TAGNAME="latexos"
                TAGVERSION="temp"

                cd LaTexOS
                docker buildx build --platform linux/amd64 --tag ${TAGNAME}:${TAGVERSION} --load .
  
            - name: Save Docker image to archive
              run: docker save latexos:temp -o latexos_temp.tar
          
            - name: Upload Docker image as artifact
              uses: actions/upload-artifact@v2
              with:
                name: latexos_temp_image
                path: latexos_temp.tar

    test:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download Docker image artifact
              uses: actions/download-artifact@v2
              with:
                name: latexos_temp_image
                path: .
        
            - name: Load Docker image # from file
              run: docker load -i latexos_temp.tar

            - name: Build LaTeX Test document
              run: |
                cd LaTexOS/testfiles/
                make all

            - name: Verify PDF
              run: |
                # TODO verify the PDF
                # - Use a tool like pdfinfo to check the PDF's metadata
                # - If the verification fails, make sure to return a non-zero exit code to indicate failure
                exit 0

    push:
        needs: test
        runs-on: ubuntu-latest
        if: ${{ needs.test.result == 'success' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Load Docker image
              run: docker load -i latexos:temp

            - name: Tag and push image to Docker Hub
              run: |
                DOCKERHUB_TAG="${{ secrets.DOCKERHUB_USERNAME }}/latexos"
                DOCKERHUB_VERSION=15.5.3
                if [ "${{ github.event_name }}" == "pull_request" ]; then
                    DOCKERHUB_VERSION="${TAGVERSION}-testing"
                fi
                docker tag latexos:temp ${DOCKERHUB_TAG}:${DOCKERHUB_VERSION}
                docker push ${DOCKERHUB_TAG}:${DOCKERHUB_VERSION}
