name: Build Docker Image

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        #runs-on: opensuse/leap
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build Docker image
              run: |
                TAGNAME="ghcr.io/${{ github.repository_owner }}/latexos"
                TAGVERSION="15.5.3"
                    
                cd LaTexOS
                if [ "${{ github.event_name }}" == "pull_request" ]; then
                    TAGVERSION="${TAGVERSION}-testing"
                fi
                docker buildx build --platform linux/amd64 --tag ${TAGNAME}:${TAGVERSION} --tag ${TAGNAME}:latest --push .

            - name: Save image digest to file
              run: |
                echo "::set-output name=digest::$(docker inspect --format='{{index .RepoDigests 0}}' ${TAGNAME}:${TAGVERSION})"
                id: build_output
