name: "Test LaTexOS Docker Image"

on:
    workflow_run:
        workflows: ["Build LaTexOS Docker Image"]
        types:
            - completed

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download Docker image artifact
              uses: actions/download-artifact@v2
              with:
                name: latexos_temp_image
                path: .
        
            - name: Load Docker image # from file
              run: docker load -i latexos_temp.tar

            - name: Build LaTeX Test document
              run: |
                cd LaTexOS/testfiles/
                make all

            - name: Verify PDF
              run: |
                # TODO verify the PDF
                # - Use a tool like pdfinfo to check the PDF's metadata
                # - If the verification fails, make sure to return a non-zero exit code to indicate failure
                exit 0
