name: "Push LaTexOS Docker Image"

on:
    workflow_run:
        workflows: ["Test LaTexOS Docker Image"]
        types:
            - completed

jobs:
    push:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Load Docker image
              run: docker load -i latexos:temp

            - name: Tag and push image to Docker Hub
              run: |
                DOCKERHUB_TAG="${{ secrets.DOCKERHUB_USERNAME }}/latexos"
                DOCKERHUB_VERSION=15.5.3
                if [ "${{ github.event_name }}" == "pull_request" ]; then
                    DOCKERHUB_VERSION="${TAGVERSION}-testing"
                fi
                docker tag latexos:temp ${DOCKERHUB_TAG}:${DOCKERHUB_VERSION}
                docker push ${DOCKERHUB_TAG}:${DOCKERHUB_VERSION}
